import {builtinModules} from "node:module";
import process from "node:process";
import {build, context} from "esbuild";

const production = process.argv[2] === "production";
const nodeBuiltins = builtinModules.flatMap((name) => [name, `node:${name}`]);
const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...nodeBuiltins,
];

const options = {
	banner: {js: "/* Generated by esbuild; edit the files in src/ instead. */"},
	bundle: true,
	entryPoints: {main: "src/main.ts", styles: "src/styles.css"},
	external,
	format: "cjs",
	logLevel: "info",
	outdir: ".",
	sourcemap: production ? false : "inline",
	target: "es2018",
	treeShaking: true,
};

try {
	if (production) {
		await build(options);
	} else {
		await (await context(options)).watch();
	}
} catch {
	process.exitCode = 1;
}
